//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodGroupStock
    {
        public int Id { get; set; }
        public string BBUsername { get; set; }
        public string BloodGroupName { get; set; }
        public int Amount { get; set; }
    
        public virtual BloodBank BloodBank { get; set; }
    }
}
